import { PasswordService } from './password.service';
import type { ConfigService } from '@nestjs/config';

// Low cost parameters keep the suite fast. verify() reads the parameters out of each
// stored hash, so this does not weaken what the tests prove.
const config = (N = 2048): ConfigService =>
  ({
    get: (key: string, fallback: number) => (key === 'SCRYPT_N' ? N : fallback),
  }) as unknown as ConfigService;

describe('PasswordService', () => {
  const service = new PasswordService(config());

  it('produces the documented format', () => {
    const hash = service.hash('Dev!2026');
    const parts = hash.split('$');
    expect(parts[0]).toBe('scrypt');
    expect(parts).toHaveLength(6);
    expect(hash).not.toContain('Dev!2026');
  });

  it('salts, so the same password never hashes twice the same way', () => {
    expect(service.hash('Dev!2026')).not.toBe(service.hash('Dev!2026'));
  });

  it('verifies a correct password and rejects a wrong one', () => {
    const hash = service.hash('Dev!2026');
    expect(service.verify('Dev!2026', hash)).toBe(true);
    expect(service.verify('dev!2026', hash)).toBe(false);
    expect(service.verify('', hash)).toBe(false);
  });

  it('accepts a hash written by prisma/seed.mjs', () => {
    // Generated by the seed's own hashPassword for the password Dev!2026. If the two
    // implementations ever drift apart, every seeded account is locked out, so this
    // fixture is the guard against that happening quietly.
    const fromSeed =
      'scrypt$16384$8$1$csPYwscXeZncc+5ACLA34A==$DZV+zXcOrB8m/E5spnrOtixb7XL7PkBfJfgBwfI1Prudvn4eQVIsQNlNJbK0NzfAIlo5RyKpDEBY3aX1EC46ag==';
    expect(service.verify('Dev!2026', fromSeed)).toBe(true);
    expect(service.verify('wrong', fromSeed)).toBe(false);
  });

  it('returns false rather than throwing on a corrupt stored hash', () => {
    for (const bad of [
      '',
      'not-a-hash',
      'scrypt$x$y$z$q$r',
      'bcrypt$16384$8$1$a$b',
      'scrypt$16384$8$1$a$',
    ]) {
      expect(service.verify('Dev!2026', bad)).toBe(false);
    }
  });

  it('flags a hash made with weaker parameters than current policy', () => {
    const weak = new PasswordService(config(1024)).hash('Dev!2026');
    expect(new PasswordService(config(16384)).needsRehash(weak)).toBe(true);
    expect(service.needsRehash(service.hash('Dev!2026'))).toBe(false);
    expect(service.needsRehash('garbage')).toBe(true);
  });
});
